### ISSUE TITLE
Adopt to tensorflow 0.12

### ISSUE THREAD

**Issue by chaitjo** [mkroutikov/tf-lstm-char-cnn#6]
Hi! Can you please update your code to be compatible with the latest tensorflow version?

I made all the suggested changes that were prompted by warnings when running  `train.py`, `model.py` and `data_reader.py`. Then on running `train.py`, I got the following output- (The dataset is my own)
```
$ python train.py
reading train
reading valid
reading test

actual longest token length is: 30
size of word vocabulary: 43960
size of char vocabulary: 650
number of tokens in train: 593645
number of tokens in valid: 20332
number of tokens in test: 16640
initialized all dataset readers
Traceback (most recent call last):
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _do_call
    return fn(*args)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 1003, in _run_fn
    status, run_metadata)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Model/Embedding/char_embedding
         [[Node: Model/Embedding/ScatterUpdate = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@Model/Embedding/char_embedding"], use_locking=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Model/Embedding/char_embedding, Model/Embedding/ScatterUpdate/indices, Model/Embedding/Const)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 248, in <module>
    tf.app.run()
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\platform\app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train.py", line 146, in main
    session.run(train_model.clear_char_embedding_padding)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Model/Embedding/char_embedding
         [[Node: Model/Embedding/ScatterUpdate = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@Model/Embedding/char_embedding"], use_locking=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Model/Embedding/char_embedding, Model/Embedding/ScatterUpdate/indices, Model/Embedding/Const)]]

Caused by op 'Model/Embedding/ScatterUpdate', defined at:
  File "train.py", line 248, in <module>
    tf.app.run()
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\platform\app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train.py", line 111, in main
    dropout=FLAGS.dropout)
  File "C:\Users\developer\Desktop\tf-lstm-char-cnn-master\model.py", line 136, in inference_graph
    clear_char_embedding_padding = tf.scatter_update(char_embedding, [0], tf.constant(0.0, shape=[1, char_embed_size]))
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 617, in scatter_update
    name=name)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\framework\ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Model/Embedding/char_embedding
         [[Node: Model/Embedding/ScatterUpdate = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@Model/Embedding/char_embedding"], use_locking=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Model/Embedding/char_embedding, Model/Embedding/ScatterUpdate/indices, Model/Embedding/Const)]]
```

**Comment by mkroutikov** [comment]
Code works as-in in TF 0.12. Some deprecation warnings will be fixed.

```
(tensorflow-0.12) mike@animal:~/git/tf-lstm-char-cnn$ python train.py 
Created training directory cv
reading train
reading valid
reading test

actual longest token length is: 21
size of word vocabulary: 10000
size of char vocabulary: 51
number of tokens in train: 929589
number of tokens in valid: 73760
number of tokens in test: 82430
initialized all dataset readers
WARNING:tensorflow:From train.py:145 in main.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Created and initialized fresh model. Size: 19367965
WARNING:tensorflow:From train.py:149 in main.: SummaryWriter.__init__ (from tensorflow.python.training.summary_io) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.
     5: 0 [    5/ 1327], train_loss/perplexity = 8.02709198/3062.8220215 secs/batch = 2.7459s, grad.norm=23.00387383
    10: 0 [   10/ 1327], train_loss/perplexity = 13.61855984/821231.1250000 secs/batch = 2.7579s, grad.norm=208.29020691
    15: 0 [   15/ 1327], train_loss/perplexity = 7.54854059/1897.9708252 secs/batch = 2.5421s, grad.norm=10.23751926
    20: 0 [   20/ 1327], train_loss/perplexity = 7.79379892/2425.5144043 secs/batch = 3.0725s, grad.norm=20.58797455
    25: 0 [   25/ 1327], train_loss/perplexity = 7.17662811/1308.4887695 secs/ba
```

**Comment by mkroutikov** [comment]
My guess is that you did not run the initializer. You can either revert to the GitHub code (and it will work), or wait for me to fix the deprecation warnings...

**Comment by chaitjo** [comment]
It worked. Thanks a lot for the fix and the awesome implementation!
