### ISSUE TITLE
Unable to load model

### ISSUE THREAD

**Issue by chaitjo** [mkroutikov/tf-lstm-char-cnn#8]
I was unable to load a partially trained model using `train.py` and `generate.py`.

During training, 3 files were generated- epoch0xx_x.xxxx.model.meta, epoch0xx_x.xxxx.model.index, epoch0xx_x.xxxx.model.data-00000-of-00001 (large file).

In your documentation, you mention that we can load a model using `--load_model cv/epoch0xx_x.xxxx.model`, but no .model file is generated for me. Could this be a tf 0.12 issue?

Here's the output from generate.py-
```
$ python generate.py --load_model='cv/epoch014_4.8191.model.data-00000-of-00001'
reading train
reading valid
reading test

actual longest token length is: 30
size of word vocabulary: 43173
size of char vocabulary: 92
number of tokens in train: 590861
number of tokens in valid: 19115
number of tokens in test: 16278
initialized test dataset reader
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Data loss: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _do_call
    return fn(*args)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 1003, in _run_fn
    status, run_metadata)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2_23 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_23/tensor_names, save/RestoreV2_23/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate.py", line 117, in <module>
    tf.app.run()
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\platform\app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "generate.py", line 84, in main
    saver.restore(session, FLAGS.load_model)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\training\saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\client\session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2_23 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_23/tensor_names, save/RestoreV2_23/shape_and_slices)]]

Caused by op 'save/RestoreV2_23', defined at:
  File "generate.py", line 117, in <module>
    tf.app.run()
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\platform\app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "generate.py", line 83, in main
    saver = tf.train.Saver()
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\training\saver.py", line 1000, in __init__
    self.build()
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\training\saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\training\saver.py", line 624, in build
    restore_sequentially, reshape)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\training\saver.py", line 361, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\training\saver.py", line 200, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 441, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\framework\ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\developer\Anaconda2\envs\tf_cpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

DataLossError (see above for traceback): Unable to open table file cv\epoch014_4.8191.model.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2_23 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_23/tensor_names, save/RestoreV2_23/shape_and_slices)]]
```

**Comment by chaitjo** [comment]
Solved it by renaming epoch0xx_x.xxxx.model.data-00000-of-00001 to epoch0xx_x.xxxx.model!
